name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [ main ]

jobs:
  android-lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run android lint check
        run: ./gradlew lintDebug